/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Game.Units.AUnit;
import javax.swing.Icon;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author DimamoN
 */
public class BattleFrame extends javax.swing.JFrame {

    /**
     * Creates new form BattleFrame
     */
    public BattleFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logPanel = new javax.swing.JPanel();
        labelBattleLog = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        battleLogTextArea = new javax.swing.JTextArea();
        hero1Panel = new javax.swing.JPanel();
        labelAttacking = new javax.swing.JLabel();
        attackerName = new javax.swing.JTextField();
        labelHero1HP = new javax.swing.JLabel();
        labelHero1Str = new javax.swing.JLabel();
        labelHero1Agl = new javax.swing.JLabel();
        hero1Str = new javax.swing.JTextField();
        hero1Agl = new javax.swing.JTextField();
        hero1HP = new javax.swing.JTextField();
        labelHero1Dmg = new javax.swing.JLabel();
        labelHero1Def = new javax.swing.JLabel();
        hero1Dmg = new javax.swing.JTextField();
        hero1Def = new javax.swing.JTextField();
        labelHero1Weapon = new javax.swing.JLabel();
        labelHero1Armor = new javax.swing.JLabel();
        hero1Weapon = new javax.swing.JTextField();
        hero1Armor = new javax.swing.JTextField();
        hero1Image = new javax.swing.JLabel();
        hero1ArmorImage = new javax.swing.JLabel();
        hero1WeaponImage = new javax.swing.JLabel();
        hero2Panel = new javax.swing.JPanel();
        labelDefencing = new javax.swing.JLabel();
        defencerName = new javax.swing.JTextField();
        labelHero2Str1 = new javax.swing.JLabel();
        labelHero2Agl = new javax.swing.JLabel();
        labelHero2HP = new javax.swing.JLabel();
        hero2HP = new javax.swing.JTextField();
        hero2Agl = new javax.swing.JTextField();
        hero2Str = new javax.swing.JTextField();
        labelHero2Def = new javax.swing.JLabel();
        labelHero2Dmg = new javax.swing.JLabel();
        hero2Dmg = new javax.swing.JTextField();
        hero2Def = new javax.swing.JTextField();
        hero2Armor = new javax.swing.JTextField();
        labelHero2Armor = new javax.swing.JLabel();
        labelHero2Weapon = new javax.swing.JLabel();
        hero2Weapon = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(750, 600));

        labelBattleLog.setText("Лог Битвы:");

        battleLogTextArea.setEditable(false);
        battleLogTextArea.setColumns(20);
        battleLogTextArea.setRows(5);
        jScrollPane1.setViewportView(battleLogTextArea);

        javax.swing.GroupLayout logPanelLayout = new javax.swing.GroupLayout(logPanel);
        logPanel.setLayout(logPanelLayout);
        logPanelLayout.setHorizontalGroup(
            logPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(logPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(logPanelLayout.createSequentialGroup()
                        .addComponent(labelBattleLog)
                        .addContainerGap(834, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)))
        );
        logPanelLayout.setVerticalGroup(
            logPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelBattleLog)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                .addContainerGap())
        );

        hero1Panel.setBackground(new java.awt.Color(240, 240, 250));
        hero1Panel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        labelAttacking.setText("Атакует");

        attackerName.setEditable(false);
        attackerName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        attackerName.setText("Имя атакующего");
        attackerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attackerNameActionPerformed(evt);
            }
        });

        labelHero1HP.setText("Здоровье");

        labelHero1Str.setText("Сила");

        labelHero1Agl.setText("Ловкость");

        hero1Str.setEditable(false);
        hero1Str.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        hero1Str.setText("Сила");
        hero1Str.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hero1StrActionPerformed(evt);
            }
        });

        hero1Agl.setEditable(false);
        hero1Agl.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        hero1Agl.setText("Ловкость");
        hero1Agl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hero1AglActionPerformed(evt);
            }
        });

        hero1HP.setEditable(false);
        hero1HP.setForeground(new java.awt.Color(255, 0, 0));
        hero1HP.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        hero1HP.setText("Здоровье");
        hero1HP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hero1HPActionPerformed(evt);
            }
        });

        labelHero1Dmg.setText("Урон");

        labelHero1Def.setText("Броня");

        hero1Dmg.setEditable(false);
        hero1Dmg.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        hero1Dmg.setText("Урон");
        hero1Dmg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hero1DmgActionPerformed(evt);
            }
        });

        hero1Def.setEditable(false);
        hero1Def.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        hero1Def.setText("Броня");
        hero1Def.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hero1DefActionPerformed(evt);
            }
        });

        labelHero1Weapon.setText("Оружие");

        labelHero1Armor.setText("Защита");

        hero1Weapon.setEditable(false);
        hero1Weapon.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        hero1Weapon.setText("Оружие");
        hero1Weapon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hero1WeaponActionPerformed(evt);
            }
        });

        hero1Armor.setEditable(false);
        hero1Armor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        hero1Armor.setText("Защита");
        hero1Armor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hero1ArmorActionPerformed(evt);
            }
        });

        hero1Image.setText("hero");
        hero1Image.setMaximumSize(new java.awt.Dimension(64, 64));
        hero1Image.setMinimumSize(new java.awt.Dimension(64, 64));

        hero1ArmorImage.setText("armor");

        hero1WeaponImage.setText("weapon");

        javax.swing.GroupLayout hero1PanelLayout = new javax.swing.GroupLayout(hero1Panel);
        hero1Panel.setLayout(hero1PanelLayout);
        hero1PanelLayout.setHorizontalGroup(
            hero1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hero1PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(hero1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(hero1PanelLayout.createSequentialGroup()
                        .addComponent(hero1Image, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(hero1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(hero1PanelLayout.createSequentialGroup()
                                .addComponent(labelHero1Agl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(hero1Agl, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(hero1PanelLayout.createSequentialGroup()
                                .addComponent(labelHero1Str, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(hero1Str, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(attackerName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelAttacking, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(hero1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelHero1HP, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelHero1Def)
                            .addComponent(labelHero1Dmg))
                        .addGap(18, 18, 18)
                        .addGroup(hero1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(hero1HP)
                            .addComponent(hero1Dmg, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(hero1Def, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(hero1PanelLayout.createSequentialGroup()
                        .addGroup(hero1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelHero1Weapon, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hero1Weapon, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(hero1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(hero1Armor, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(hero1PanelLayout.createSequentialGroup()
                                .addComponent(labelHero1Armor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(hero1ArmorImage, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
            .addGroup(hero1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(hero1PanelLayout.createSequentialGroup()
                    .addGap(141, 141, 141)
                    .addComponent(hero1WeaponImage, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(193, Short.MAX_VALUE)))
        );
        hero1PanelLayout.setVerticalGroup(
            hero1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hero1PanelLayout.createSequentialGroup()
                .addGroup(hero1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(hero1PanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelAttacking)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(hero1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(attackerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelHero1HP))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(hero1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelHero1Str)
                            .addComponent(hero1Str, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelHero1Dmg))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(hero1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelHero1Agl)
                            .addComponent(hero1Agl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelHero1Def)))
                    .addGroup(hero1PanelLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(hero1Image, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hero1PanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(hero1HP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hero1Dmg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hero1Def, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(hero1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hero1ArmorImage, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelHero1Weapon)
                    .addComponent(labelHero1Armor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(hero1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hero1Armor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hero1Weapon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(hero1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hero1PanelLayout.createSequentialGroup()
                    .addContainerGap(139, Short.MAX_VALUE)
                    .addComponent(hero1WeaponImage, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(39, 39, 39)))
        );

        labelDefencing.setText("Оборона");

        defencerName.setEditable(false);
        defencerName.setText("Имя обороняющегося");

        labelHero2Str1.setText("Сила");

        labelHero2Agl.setText("Ловкость");

        labelHero2HP.setText("Здоровье");

        hero2HP.setEditable(false);
        hero2HP.setText("Здоровье");
        hero2HP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hero2HPActionPerformed(evt);
            }
        });

        hero2Agl.setEditable(false);
        hero2Agl.setText("Ловкость");
        hero2Agl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hero2AglActionPerformed(evt);
            }
        });

        hero2Str.setEditable(false);
        hero2Str.setText("Сила");
        hero2Str.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hero2StrActionPerformed(evt);
            }
        });

        labelHero2Def.setText("Броня");

        labelHero2Dmg.setText("Урон");

        hero2Dmg.setEditable(false);
        hero2Dmg.setText("Урон");
        hero2Dmg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hero2DmgActionPerformed(evt);
            }
        });

        hero2Def.setEditable(false);
        hero2Def.setText("Броня");
        hero2Def.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hero2DefActionPerformed(evt);
            }
        });

        hero2Armor.setEditable(false);
        hero2Armor.setText("Защита");

        labelHero2Armor.setText("Защита");

        labelHero2Weapon.setText("Оружие");

        hero2Weapon.setEditable(false);
        hero2Weapon.setText("Оружие");
        hero2Weapon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hero2WeaponActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout hero2PanelLayout = new javax.swing.GroupLayout(hero2Panel);
        hero2Panel.setLayout(hero2PanelLayout);
        hero2PanelLayout.setHorizontalGroup(
            hero2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hero2PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(hero2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelHero2Agl)
                    .addComponent(labelDefencing)
                    .addComponent(labelHero2HP)
                    .addComponent(labelHero2Str1)
                    .addComponent(labelHero2Armor)
                    .addComponent(labelHero2Weapon))
                .addGap(18, 18, 18)
                .addGroup(hero2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(hero2Weapon, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                    .addComponent(hero2Armor)
                    .addGroup(hero2PanelLayout.createSequentialGroup()
                        .addGroup(hero2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hero2HP, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hero2Agl, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(hero2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelHero2Def)
                            .addComponent(labelHero2Dmg))
                        .addGap(18, 18, 18)
                        .addGroup(hero2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hero2Dmg, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hero2Def, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(defencerName, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hero2Str, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        hero2PanelLayout.setVerticalGroup(
            hero2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hero2PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(hero2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDefencing)
                    .addComponent(defencerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(hero2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hero2Str, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelHero2Str1))
                .addGap(9, 9, 9)
                .addGroup(hero2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(hero2PanelLayout.createSequentialGroup()
                        .addGroup(hero2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hero2Agl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelHero2Agl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(hero2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hero2HP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelHero2HP))
                        .addGap(11, 11, 11)
                        .addGroup(hero2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelHero2Weapon)
                            .addComponent(hero2Weapon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(hero2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelHero2Armor)
                            .addComponent(hero2Armor))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(hero2PanelLayout.createSequentialGroup()
                        .addGroup(hero2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hero2Dmg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelHero2Dmg))
                        .addGap(6, 6, 6)
                        .addGroup(hero2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hero2Def, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelHero2Def))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(hero1Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(hero2Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(hero2Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(hero1Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)))
                .addComponent(logPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hero1StrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hero1StrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hero1StrActionPerformed

    private void hero1AglActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hero1AglActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hero1AglActionPerformed

    private void hero1HPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hero1HPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hero1HPActionPerformed

    private void hero1DmgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hero1DmgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hero1DmgActionPerformed

    private void hero1DefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hero1DefActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hero1DefActionPerformed

    private void hero1WeaponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hero1WeaponActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hero1WeaponActionPerformed

    private void hero1ArmorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hero1ArmorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hero1ArmorActionPerformed

    private void hero2WeaponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hero2WeaponActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hero2WeaponActionPerformed

    private void hero2DefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hero2DefActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hero2DefActionPerformed

    private void hero2DmgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hero2DmgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hero2DmgActionPerformed

    private void hero2StrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hero2StrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hero2StrActionPerformed

    private void hero2AglActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hero2AglActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hero2AglActionPerformed

    private void hero2HPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hero2HPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hero2HPActionPerformed

    private void attackerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attackerNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_attackerNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BattleFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BattleFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BattleFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BattleFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BattleFrame().setVisible(true);
            }
        });
    }
    
    //Добавить запись в боевой лог
    public void addBattleLog(String text){
  
        String oldText = this.battleLogTextArea.getText();
        
        this.battleLogTextArea.setText(oldText + "\n" + text);
    }
    
    //Установить имя атакующего на фрейме
    public void setAttackerName(String name){
       this.attackerName.setText(name);
    }
    
    //Установить имя защищающегося на фрейме
    public void setDeffencerName(String name){
       this.defencerName.setText(name);
    }

    public JTextField getHero1Agl() {
        return hero1Agl;
    }

    public JTextField getHero1Def() {
        return hero1Def;
    }

    public JTextField getHero1Dmg() {
        return hero1Dmg;
    }

    public JTextField getHero1HP() {
        return hero1HP;
    }

    public JTextField getHero1Str() {
        return hero1Str;
    }

    public JTextField getHero2Agl() {
        return hero2Agl;
    }

    public JTextField getHero2HP() {
        return hero2HP;
    }

    public JTextField getHero2Def() {
        return hero2Def;
    }

    public JTextField getHero2Dmg() {
        return hero2Dmg;
    }

    public JTextField getHero2Str() {
        return hero2Str;
    }

    public JTextField getHero1Armor() {
        return hero1Armor;
    }

    public JTextField getHero1Weapon() {
        return hero1Weapon;
    }

    public JTextField getHero2Armor() {
        return hero2Armor;
    }

    public JTextField getHero2Weapon() {
        return hero2Weapon;
    }
    
    //ИКОНКА ГЕРОЯ и Оружия
    public void setHero1Image(AUnit one) {
        this.hero1Image.setIcon(one.getImage());
        this.hero1WeaponImage.setIcon(one.getWeapon().getImage());  
        this.hero1ArmorImage.setIcon(one.getArmor().getImage()); 
    }
    
    //Установить все параметры первого персонажа
    public void setHeroesStats(AUnit one, AUnit two){
        
       this.getHero1Agl().setText(one.getAgl() + "");
       this.getHero1Str().setText(one.getStr() + "");
       this.getHero1HP().setText(one.getHp() + "");
       this.getHero1Def().setText(one.getArmor().getDef() + "");
       this.getHero1Dmg().setText(one.getStr() + one.getWeapon().getDmg() + "");
        
       this.getHero2Agl().setText(two.getAgl() + "");
       this.getHero2Str().setText(two.getStr() + "");
       this.getHero2HP().setText(two.getHp() + "");
       this.getHero2Def().setText(two.getArmor().getDef() + "");
       this.getHero2Dmg().setText(two.getStr() + two.getWeapon().getDmg() + ""); 
       
       //Оружие и броня
       this.getHero1Weapon().setText(one.getWeapon().toString());
       this.getHero1Armor().setText(one.getArmor().toString());
       
       this.getHero2Weapon().setText(two.getWeapon().toString());
       this.getHero2Armor().setText(two.getArmor().toString());
          
    }
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField attackerName;
    private javax.swing.JTextArea battleLogTextArea;
    private javax.swing.JTextField defencerName;
    private javax.swing.JTextField hero1Agl;
    private javax.swing.JTextField hero1Armor;
    private javax.swing.JLabel hero1ArmorImage;
    private javax.swing.JTextField hero1Def;
    private javax.swing.JTextField hero1Dmg;
    private javax.swing.JTextField hero1HP;
    private javax.swing.JLabel hero1Image;
    private javax.swing.JPanel hero1Panel;
    private javax.swing.JTextField hero1Str;
    private javax.swing.JTextField hero1Weapon;
    private javax.swing.JLabel hero1WeaponImage;
    private javax.swing.JTextField hero2Agl;
    private javax.swing.JTextField hero2Armor;
    private javax.swing.JTextField hero2Def;
    private javax.swing.JTextField hero2Dmg;
    private javax.swing.JTextField hero2HP;
    private javax.swing.JPanel hero2Panel;
    private javax.swing.JTextField hero2Str;
    private javax.swing.JTextField hero2Weapon;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelAttacking;
    private javax.swing.JLabel labelBattleLog;
    private javax.swing.JLabel labelDefencing;
    private javax.swing.JLabel labelHero1Agl;
    private javax.swing.JLabel labelHero1Armor;
    private javax.swing.JLabel labelHero1Def;
    private javax.swing.JLabel labelHero1Dmg;
    private javax.swing.JLabel labelHero1HP;
    private javax.swing.JLabel labelHero1Str;
    private javax.swing.JLabel labelHero1Weapon;
    private javax.swing.JLabel labelHero2Agl;
    private javax.swing.JLabel labelHero2Armor;
    private javax.swing.JLabel labelHero2Def;
    private javax.swing.JLabel labelHero2Dmg;
    private javax.swing.JLabel labelHero2HP;
    private javax.swing.JLabel labelHero2Str1;
    private javax.swing.JLabel labelHero2Weapon;
    private javax.swing.JPanel logPanel;
    // End of variables declaration//GEN-END:variables
}
