/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Game.Battle;
import Game.Damage;
import Game.Units.AUnit;
import Game.Units.SimpleMan;
import java.awt.Color;
import java.util.Random;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author DimamoN
 */
public class BattleFrame extends javax.swing.JFrame {

    //Фрем битвы персонажей
    
    //Логика битвы
    Battle battle;
    
    //Юниты
    AUnit one;
    AUnit two;
    
    //Ход битвы
    int turn = 1;
    
    //Идет ли битва
    boolean isBattle = false;
    
    /**
     * Creates new form BattleFrame
     */
    public BattleFrame(AUnit one, AUnit two) {
     
        initComponents();
        
        //Сохранение персонажей
        this.one = one;
        this.two = two;
        
        //Установка кто где стоит
        one.setAttacking(true);
        two.setAttacking(false);
        
        //Установка иконки приложения - прямой путь к иконке (можно 32х32)
        this.setIconImage(new ImageIcon("src\\Images\\icon.png").getImage());
        this.setTitle("RPG GAME");
        
        //Создание пустой битвы
        battle = new Battle();
        
        //Установка параметров и айтемов героев
        this.setupHeroesOnFrame(one, two);
        
        //Настройка окна
        this.setVisible(true);
        this.setLocation(300, 300);
        
        //Установить фокус на ФОРМУ!
        this.btnAutoFight.transferFocusUpCycle();
    }

    private BattleFrame() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logPanel = new javax.swing.JPanel();
        labelBattleLog = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        battleLogTextArea = new javax.swing.JTextArea();
        labelTurn = new javax.swing.JLabel();
        hero1Panel = new javax.swing.JPanel();
        labelAttacking = new javax.swing.JLabel();
        hero1name = new javax.swing.JTextField();
        labelHero1HP = new javax.swing.JLabel();
        labelHero1Str = new javax.swing.JLabel();
        labelHero1Agl = new javax.swing.JLabel();
        hero1Str = new javax.swing.JTextField();
        hero1Agl = new javax.swing.JTextField();
        hero1HP = new javax.swing.JTextField();
        labelHero1Dmg = new javax.swing.JLabel();
        labelHero1Def = new javax.swing.JLabel();
        hero1Dmg = new javax.swing.JTextField();
        hero1Def = new javax.swing.JTextField();
        labelHero1Weapon = new javax.swing.JLabel();
        labelHero1Armor = new javax.swing.JLabel();
        hero1Weapon = new javax.swing.JTextField();
        hero1Armor = new javax.swing.JTextField();
        hero1Image = new javax.swing.JLabel();
        hero1ArmorImage = new javax.swing.JLabel();
        hero1WeaponImage = new javax.swing.JLabel();
        hero2Panel = new javax.swing.JPanel();
        labelDefencing = new javax.swing.JLabel();
        hero2name = new javax.swing.JTextField();
        labelHero2HP = new javax.swing.JLabel();
        labelHero2Str = new javax.swing.JLabel();
        labelHero2Agl = new javax.swing.JLabel();
        hero2Str = new javax.swing.JTextField();
        hero2Agl = new javax.swing.JTextField();
        hero2HP = new javax.swing.JTextField();
        labelHero2Dmg = new javax.swing.JLabel();
        labelHero2Def = new javax.swing.JLabel();
        hero2Dmg = new javax.swing.JTextField();
        hero2Def = new javax.swing.JTextField();
        labelHero2Weapon = new javax.swing.JLabel();
        labelHero2Armor = new javax.swing.JLabel();
        hero2Weapon = new javax.swing.JTextField();
        hero2Armor = new javax.swing.JTextField();
        hero2Image = new javax.swing.JLabel();
        hero2ArmorImage = new javax.swing.JLabel();
        hero2WeaponImage = new javax.swing.JLabel();
        controlPanel = new javax.swing.JPanel();
        btnAutoFight = new javax.swing.JButton();
        btnNextTurn = new javax.swing.JButton();
        btnRestartFight = new javax.swing.JButton();
        ComboBox = new javax.swing.JComboBox<>();
        btnChangeWeapon = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        labelBattleBetween = new javax.swing.JLabel();
        labelHero1Name = new javax.swing.JLabel();
        labelHero2Name = new javax.swing.JLabel();
        labelBattleBetween1 = new javax.swing.JLabel();
        hero1StatPanel = new javax.swing.JPanel();
        labelHero1Status = new javax.swing.JLabel();
        labelHero1Hit = new javax.swing.JLabel();
        labelHero1Miss = new javax.swing.JLabel();
        labelHero1HitPerc = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        hero1Miss = new javax.swing.JLabel();
        hero1HitPerc = new javax.swing.JLabel();
        hero1Hit = new javax.swing.JLabel();
        hero1StatPanel1 = new javax.swing.JPanel();
        labelHero2Status = new javax.swing.JLabel();
        labelHero2Hit = new javax.swing.JLabel();
        labelHero2Miss = new javax.swing.JLabel();
        labelHero2HitPerc = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        hero2Miss = new javax.swing.JLabel();
        hero2HitPerc = new javax.swing.JLabel();
        hero2Hit = new javax.swing.JLabel();

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(870, 570));
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        labelBattleLog.setText("Лог Битвы:");

        battleLogTextArea.setEditable(false);
        battleLogTextArea.setColumns(20);
        battleLogTextArea.setRows(5);
        jScrollPane1.setViewportView(battleLogTextArea);

        labelTurn.setText("Ход");

        javax.swing.GroupLayout logPanelLayout = new javax.swing.GroupLayout(logPanel);
        logPanel.setLayout(logPanelLayout);
        logPanelLayout.setHorizontalGroup(
            logPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(logPanelLayout.createSequentialGroup()
                .addComponent(labelBattleLog, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelTurn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        logPanelLayout.setVerticalGroup(
            logPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(logPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelBattleLog)
                    .addComponent(labelTurn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        hero1Panel.setBackground(new java.awt.Color(240, 240, 250));
        hero1Panel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        labelAttacking.setText("Атакует");

        hero1name.setEditable(false);
        hero1name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        hero1name.setText("Имя атакующего");
        hero1name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hero1nameActionPerformed(evt);
            }
        });

        labelHero1HP.setText("Здоровье");

        labelHero1Str.setText("Сила");

        labelHero1Agl.setText("Ловкость");

        hero1Str.setEditable(false);
        hero1Str.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        hero1Str.setText("Сила");
        hero1Str.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hero1StrActionPerformed(evt);
            }
        });

        hero1Agl.setEditable(false);
        hero1Agl.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        hero1Agl.setText("Ловкость");
        hero1Agl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hero1AglActionPerformed(evt);
            }
        });

        hero1HP.setEditable(false);
        hero1HP.setForeground(new java.awt.Color(255, 0, 0));
        hero1HP.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        hero1HP.setText("Здоровье");
        hero1HP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hero1HPActionPerformed(evt);
            }
        });

        labelHero1Dmg.setText("Урон");

        labelHero1Def.setText("Броня");

        hero1Dmg.setEditable(false);
        hero1Dmg.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        hero1Dmg.setText("Урон");
        hero1Dmg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hero1DmgActionPerformed(evt);
            }
        });

        hero1Def.setEditable(false);
        hero1Def.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        hero1Def.setText("Броня");
        hero1Def.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hero1DefActionPerformed(evt);
            }
        });

        labelHero1Weapon.setText("Оружие");

        labelHero1Armor.setText("Защита");

        hero1Weapon.setEditable(false);
        hero1Weapon.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        hero1Weapon.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        hero1Weapon.setText("Оружие");
        hero1Weapon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hero1WeaponActionPerformed(evt);
            }
        });

        hero1Armor.setEditable(false);
        hero1Armor.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        hero1Armor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        hero1Armor.setText("Защита");
        hero1Armor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hero1ArmorActionPerformed(evt);
            }
        });

        hero1Image.setText("hero");
        hero1Image.setMaximumSize(new java.awt.Dimension(64, 64));
        hero1Image.setMinimumSize(new java.awt.Dimension(64, 64));

        hero1ArmorImage.setText("armor");

        hero1WeaponImage.setText("weapon");

        javax.swing.GroupLayout hero1PanelLayout = new javax.swing.GroupLayout(hero1Panel);
        hero1Panel.setLayout(hero1PanelLayout);
        hero1PanelLayout.setHorizontalGroup(
            hero1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hero1PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(hero1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(hero1PanelLayout.createSequentialGroup()
                        .addComponent(hero1Image, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(hero1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(hero1PanelLayout.createSequentialGroup()
                                .addComponent(labelHero1Agl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(hero1Agl, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(hero1PanelLayout.createSequentialGroup()
                                .addComponent(labelHero1Str, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(hero1Str, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(hero1name, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelAttacking, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(hero1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelHero1HP, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelHero1Def)
                            .addComponent(labelHero1Dmg))
                        .addGap(18, 18, 18)
                        .addGroup(hero1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(hero1HP)
                            .addComponent(hero1Dmg, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(hero1Def, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(hero1PanelLayout.createSequentialGroup()
                        .addGroup(hero1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelHero1Weapon, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hero1Weapon, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(hero1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(hero1Armor, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(hero1PanelLayout.createSequentialGroup()
                                .addComponent(labelHero1Armor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(hero1ArmorImage, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
            .addGroup(hero1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(hero1PanelLayout.createSequentialGroup()
                    .addGap(141, 141, 141)
                    .addComponent(hero1WeaponImage, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(193, Short.MAX_VALUE)))
        );
        hero1PanelLayout.setVerticalGroup(
            hero1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hero1PanelLayout.createSequentialGroup()
                .addGroup(hero1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(hero1PanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelAttacking)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(hero1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hero1name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelHero1HP))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(hero1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelHero1Str)
                            .addComponent(hero1Str, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelHero1Dmg))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(hero1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelHero1Agl)
                            .addComponent(hero1Agl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelHero1Def)))
                    .addGroup(hero1PanelLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(hero1Image, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hero1PanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(hero1HP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hero1Dmg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hero1Def, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(hero1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hero1ArmorImage, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelHero1Weapon)
                    .addComponent(labelHero1Armor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(hero1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hero1Armor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hero1Weapon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(hero1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hero1PanelLayout.createSequentialGroup()
                    .addContainerGap(139, Short.MAX_VALUE)
                    .addComponent(hero1WeaponImage, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(39, 39, 39)))
        );

        hero2Panel.setBackground(new java.awt.Color(240, 240, 250));
        hero2Panel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        labelDefencing.setText("Защищается");

        hero2name.setEditable(false);
        hero2name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        hero2name.setText("Имя атакующего");
        hero2name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hero2nameActionPerformed(evt);
            }
        });

        labelHero2HP.setText("Здоровье");

        labelHero2Str.setText("Сила");

        labelHero2Agl.setText("Ловкость");

        hero2Str.setEditable(false);
        hero2Str.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        hero2Str.setText("Сила");
        hero2Str.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hero2StrActionPerformed(evt);
            }
        });

        hero2Agl.setEditable(false);
        hero2Agl.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        hero2Agl.setText("Ловкость");
        hero2Agl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hero2AglActionPerformed(evt);
            }
        });

        hero2HP.setEditable(false);
        hero2HP.setForeground(new java.awt.Color(255, 0, 0));
        hero2HP.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        hero2HP.setText("Здоровье");
        hero2HP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hero2HPActionPerformed(evt);
            }
        });

        labelHero2Dmg.setText("Урон");

        labelHero2Def.setText("Броня");

        hero2Dmg.setEditable(false);
        hero2Dmg.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        hero2Dmg.setText("Урон");
        hero2Dmg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hero2DmgActionPerformed(evt);
            }
        });

        hero2Def.setEditable(false);
        hero2Def.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        hero2Def.setText("Броня");
        hero2Def.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hero2DefActionPerformed(evt);
            }
        });

        labelHero2Weapon.setText("Оружие");

        labelHero2Armor.setText("Защита");

        hero2Weapon.setEditable(false);
        hero2Weapon.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        hero2Weapon.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        hero2Weapon.setText("Оружие");
        hero2Weapon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hero2WeaponActionPerformed(evt);
            }
        });

        hero2Armor.setEditable(false);
        hero2Armor.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        hero2Armor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        hero2Armor.setText("Защита");
        hero2Armor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hero2ArmorActionPerformed(evt);
            }
        });

        hero2Image.setText("hero");
        hero2Image.setMaximumSize(new java.awt.Dimension(64, 64));
        hero2Image.setMinimumSize(new java.awt.Dimension(64, 64));

        hero2ArmorImage.setText("armor");

        hero2WeaponImage.setText("weapon");

        javax.swing.GroupLayout hero2PanelLayout = new javax.swing.GroupLayout(hero2Panel);
        hero2Panel.setLayout(hero2PanelLayout);
        hero2PanelLayout.setHorizontalGroup(
            hero2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hero2PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(hero2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(hero2PanelLayout.createSequentialGroup()
                        .addComponent(hero2Image, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(hero2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(hero2PanelLayout.createSequentialGroup()
                                .addComponent(labelHero2Agl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(hero2Agl, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(hero2PanelLayout.createSequentialGroup()
                                .addComponent(labelHero2Str, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(hero2Str, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(hero2name, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelDefencing, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(hero2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelHero2HP, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelHero2Def)
                            .addComponent(labelHero2Dmg))
                        .addGap(18, 18, 18)
                        .addGroup(hero2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(hero2HP)
                            .addComponent(hero2Dmg, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(hero2Def, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(hero2PanelLayout.createSequentialGroup()
                        .addGroup(hero2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelHero2Weapon, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hero2Weapon, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(hero2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(hero2Armor, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(hero2PanelLayout.createSequentialGroup()
                                .addComponent(labelHero2Armor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(hero2ArmorImage, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
            .addGroup(hero2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(hero2PanelLayout.createSequentialGroup()
                    .addGap(141, 141, 141)
                    .addComponent(hero2WeaponImage, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(193, Short.MAX_VALUE)))
        );
        hero2PanelLayout.setVerticalGroup(
            hero2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hero2PanelLayout.createSequentialGroup()
                .addGroup(hero2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(hero2PanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelDefencing)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(hero2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hero2name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelHero2HP))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(hero2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelHero2Str)
                            .addComponent(hero2Str, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelHero2Dmg))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(hero2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelHero2Agl)
                            .addComponent(hero2Agl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelHero2Def)))
                    .addGroup(hero2PanelLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(hero2Image, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hero2PanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(hero2HP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hero2Dmg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hero2Def, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(hero2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hero2ArmorImage, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelHero2Weapon)
                    .addComponent(labelHero2Armor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(hero2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hero2Armor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hero2Weapon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(hero2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hero2PanelLayout.createSequentialGroup()
                    .addContainerGap(139, Short.MAX_VALUE)
                    .addComponent(hero2WeaponImage, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(39, 39, 39)))
        );

        btnAutoFight.setText("Автобой (A)");
        btnAutoFight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAutoFightActionPerformed(evt);
            }
        });

        btnNextTurn.setText("Следующий ход");
        btnNextTurn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextTurnActionPerformed(evt);
            }
        });

        btnRestartFight.setText("*Рестарт* (R)");
        btnRestartFight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestartFightActionPerformed(evt);
            }
        });
        btnRestartFight.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnRestartFightKeyPressed(evt);
            }
        });

        ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Клинок", "Меч", "Длинный меч", "Секира", "Огрская секира" }));
        ComboBox.setEnabled(false);
        ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxActionPerformed(evt);
            }
        });

        btnChangeWeapon.setText("Изменить оружие");
        btnChangeWeapon.setEnabled(false);
        btnChangeWeapon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeWeaponActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlPanelLayout = new javax.swing.GroupLayout(controlPanel);
        controlPanel.setLayout(controlPanelLayout);
        controlPanelLayout.setHorizontalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAutoFight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNextTurn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRestartFight, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnChangeWeapon, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                    .addComponent(ComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        controlPanelLayout.setVerticalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAutoFight, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNextTurn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRestartFight)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnChangeWeapon, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnAutoFight.getAccessibleContext().setAccessibleDescription("");

        labelBattleBetween.setText("Битва между:");

        labelHero1Name.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelHero1Name.setText("Герой 1");

        labelHero2Name.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelHero2Name.setText("Герой 2");

        labelBattleBetween1.setText("и");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(labelBattleBetween)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelHero1Name, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelBattleBetween1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelHero2Name, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelBattleBetween)
                    .addComponent(labelHero1Name)
                    .addComponent(labelHero2Name)
                    .addComponent(labelBattleBetween1))
                .addContainerGap())
        );

        hero1StatPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        labelHero1Status.setText("Статус:");
        labelHero1Status.setEnabled(false);

        labelHero1Hit.setText("Попаданий:");

        labelHero1Miss.setText("Промахов:");

        labelHero1HitPerc.setText("Процент:");

        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("Статус");
        jTextField1.setEnabled(false);

        hero1Miss.setText("0");

        hero1HitPerc.setText("0");

        hero1Hit.setText("0");

        javax.swing.GroupLayout hero1StatPanelLayout = new javax.swing.GroupLayout(hero1StatPanel);
        hero1StatPanel.setLayout(hero1StatPanelLayout);
        hero1StatPanelLayout.setHorizontalGroup(
            hero1StatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hero1StatPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(hero1StatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(hero1StatPanelLayout.createSequentialGroup()
                        .addComponent(labelHero1Status)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(hero1StatPanelLayout.createSequentialGroup()
                        .addGroup(hero1StatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hero1StatPanelLayout.createSequentialGroup()
                                .addGroup(hero1StatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelHero1Miss)
                                    .addComponent(labelHero1HitPerc))
                                .addGap(18, 18, 18))
                            .addGroup(hero1StatPanelLayout.createSequentialGroup()
                                .addComponent(labelHero1Hit)
                                .addGap(11, 11, 11)))
                        .addGroup(hero1StatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(hero1Hit, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                            .addComponent(hero1Miss, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                            .addComponent(hero1HitPerc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        hero1StatPanelLayout.setVerticalGroup(
            hero1StatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hero1StatPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(hero1StatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelHero1Status, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(hero1StatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelHero1Hit)
                    .addComponent(hero1Hit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(hero1StatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelHero1Miss)
                    .addComponent(hero1Miss))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(hero1StatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelHero1HitPerc)
                    .addComponent(hero1HitPerc))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        hero1StatPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        labelHero2Status.setText("Статус:");
        labelHero2Status.setEnabled(false);

        labelHero2Hit.setText("Попаданий:");

        labelHero2Miss.setText("Промахов:");

        labelHero2HitPerc.setText("Процент:");

        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("Статус");
        jTextField2.setEnabled(false);

        hero2Miss.setText("0");

        hero2HitPerc.setText("0");

        hero2Hit.setText("0");

        javax.swing.GroupLayout hero1StatPanel1Layout = new javax.swing.GroupLayout(hero1StatPanel1);
        hero1StatPanel1.setLayout(hero1StatPanel1Layout);
        hero1StatPanel1Layout.setHorizontalGroup(
            hero1StatPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hero1StatPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(hero1StatPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(hero1StatPanel1Layout.createSequentialGroup()
                        .addComponent(labelHero2Status)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(hero1StatPanel1Layout.createSequentialGroup()
                        .addGroup(hero1StatPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hero1StatPanel1Layout.createSequentialGroup()
                                .addGroup(hero1StatPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelHero2Miss)
                                    .addComponent(labelHero2HitPerc))
                                .addGap(18, 18, 18))
                            .addGroup(hero1StatPanel1Layout.createSequentialGroup()
                                .addComponent(labelHero2Hit)
                                .addGap(11, 11, 11)))
                        .addGroup(hero1StatPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(hero2Hit, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                            .addComponent(hero2Miss, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                            .addComponent(hero2HitPerc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(206, Short.MAX_VALUE))
        );
        hero1StatPanel1Layout.setVerticalGroup(
            hero1StatPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hero1StatPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(hero1StatPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelHero2Status, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(hero1StatPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelHero2Hit)
                    .addComponent(hero2Hit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(hero1StatPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelHero2Miss)
                    .addComponent(hero2Miss))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(hero1StatPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelHero2HitPerc)
                    .addComponent(hero2HitPerc))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(controlPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(logPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(hero1StatPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(hero1Panel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hero2Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hero1StatPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hero1Panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hero2Panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(hero1StatPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hero1StatPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(controlPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(logPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hero1StrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hero1StrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hero1StrActionPerformed

    private void hero1AglActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hero1AglActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hero1AglActionPerformed

    private void hero1HPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hero1HPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hero1HPActionPerformed

    private void hero1DmgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hero1DmgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hero1DmgActionPerformed

    private void hero1DefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hero1DefActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hero1DefActionPerformed

    private void hero1WeaponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hero1WeaponActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hero1WeaponActionPerformed

    private void hero1ArmorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hero1ArmorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hero1ArmorActionPerformed

    private void hero1nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hero1nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hero1nameActionPerformed

    private void hero2nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hero2nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hero2nameActionPerformed

    private void hero2StrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hero2StrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hero2StrActionPerformed

    private void hero2AglActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hero2AglActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hero2AglActionPerformed

    private void hero2HPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hero2HPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hero2HPActionPerformed

    private void hero2DmgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hero2DmgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hero2DmgActionPerformed

    private void hero2DefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hero2DefActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hero2DefActionPerformed

    private void hero2WeaponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hero2WeaponActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hero2WeaponActionPerformed

    private void hero2ArmorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hero2ArmorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hero2ArmorActionPerformed

    //Изменить оружие DONT WORKING
    private void btnChangeWeaponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeWeaponActionPerformed

        switch(this.ComboBox.getSelectedIndex()){
            
            case 0: this.hero1WeaponImage.setIcon(new ImageIcon("src\\Images\\Weapons\\dagger.png")); break;
            case 1: this.hero1WeaponImage.setIcon(new ImageIcon("src\\Images\\Weapons\\sword.png")); break;
            case 2: this.hero1WeaponImage.setIcon(new ImageIcon("src\\Images\\Weapons\\longSword.png")); break;
            case 3: this.hero1WeaponImage.setIcon(new ImageIcon("src\\Images\\Weapons\\axe.png")); break;
            case 4: this.hero1WeaponImage.setIcon(new ImageIcon("src\\Images\\Weapons\\axeDoubleEdge.png")); break;
            default:
            
        }
  
    }//GEN-LAST:event_btnChangeWeaponActionPerformed

    private void ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxActionPerformed

    //Следующий ход в битве
    private void btnNextTurnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextTurnActionPerformed
       this.nextRound();
    }//GEN-LAST:event_btnNextTurnActionPerformed

    private void btnAutoFightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAutoFightActionPerformed
        this.autoFight(this.one, this.two);
    }//GEN-LAST:event_btnAutoFightActionPerformed

    private void btnRestartFightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestartFightActionPerformed
        this.restartBattle(one, two);
    }//GEN-LAST:event_btnRestartFightActionPerformed

    //РЕСТАРТ, привязка к кнопке R   DONT WORK
    private void btnRestartFightKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnRestartFightKeyPressed
       
        
        this.labelHero1Name.setText(evt.getKeyCode()+"");
        
        
        //Если пробел - ничего не делать
        if (evt.getKeyCode() == 32 ) {};
                
        if(evt.getKeyCode() == 82){
            this.restartBattle(one, two);
            
            //Фокус на форму
            this.btnAutoFight.transferFocusUpCycle();
        }
        
        
    }//GEN-LAST:event_btnRestartFightKeyPressed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
       
//        this.labelHero1Name.setText(evt.getKeyCode()+"");
        
        switch(evt.getKeyCode()){
            case 65: this.autoFight(one, two); break;
            case 82: this.restartBattle(one, two); break;
            case 32: this.nextRound(); break;
        }
      
    }//GEN-LAST:event_formKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BattleFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BattleFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BattleFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BattleFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BattleFrame().setVisible(true);
            }
        });
    }
    
    //Добавить запись в боевой лог
    public void addBattleLog(String text){
  
        String oldText = this.battleLogTextArea.getText();
        
        this.battleLogTextArea.setText(oldText + "\n" + text);
    }

    //Очистить лог битвы
    public void clearBattleLog(){
        this.battleLogTextArea.setText("");
    }
    
    public JTextField getHero1Agl() {
        return hero1Agl;
    }

    public JTextField getHero1Def() {
        return hero1Def;
    }

    public JTextField getHero1Dmg() {
        return hero1Dmg;
    }

    public JTextField getHero1HP() {
        return hero1HP;
    }

    public JTextField getHero1Str() {
        return hero1Str;
    }

    public JTextField getHero2Agl() {
        return hero2Agl;
    }

    public JTextField getHero2HP() {
        return hero2HP;
    }

    public JTextField getHero2Def() {
        return hero2Def;
    }

    public JTextField getHero2Dmg() {
        return hero2Dmg;
    }

    public JTextField getHero2Str() {
        return hero2Str;
    }

    public JTextField getHero1Armor() {
        return hero1Armor;
    }

    public JTextField getHero1Weapon() {
        return hero1Weapon;
    }

    public JTextField getHero2Armor() {
        return hero2Armor;
    }

    public JTextField getHero2Weapon() {
        return hero2Weapon;
    }
    
    //Настройка фреймов для начала боя
    public void battleStartSetup(){
        
        //Начало битвыы
        this.isBattle = true;
        
        //Включить конпки
        this.btnNextTurn.setEnabled(true);
        this.btnAutoFight.setEnabled(true);
        
    }
    
    //Настройка фреймов для конца боя
    public void battleEndSetup(){
        
        //Конец битвы
        this.isBattle = false;
        
        //Включить конпки
        this.btnNextTurn.setEnabled(false);
        this.btnAutoFight.setEnabled(false);
  
    }
    
    //Полная настройка героев!
    public void setupHeroesOnFrame(AUnit one, AUnit two){
        //Имена
        this.hero1name.setText(one.getName());
        this.hero2name.setText(two.getName());
        
        //На лейблы сверху
        this.labelHero1Name.setText(one.getName());
        this.labelHero2Name.setText(two.getName());
        
        //Статы
        this.setHeroesStats(one, two);
        
        //Картинки
        this.setHeroesImages(one, two);
        
        //***
        
        //Ход битвы
        
        if(isBattle) this.labelTurn.setText("Следующий ход №" + turn);

    }
   
    //Установить иконки, оружия и доспехи героев
    public void setHeroesImages(AUnit one, AUnit two) {
        
        //Для первого
        this.hero1Image.setIcon(one.getImage());
        this.hero1WeaponImage.setIcon(one.getWeapon().getImage());  
        this.hero1ArmorImage.setIcon(one.getArmor().getImage()); 
        
        //Для второго
        this.hero2Image.setIcon(two.getImage());
        this.hero2WeaponImage.setIcon(two.getWeapon().getImage());  
        this.hero2ArmorImage.setIcon(two.getArmor().getImage());
        
    }
    
    //Установить все параметры первого персонажа
    public void setHeroesStats(AUnit one, AUnit two){
        
       this.getHero1Agl().setText(one.getAgl() + "");
       this.getHero1Str().setText(one.getStr() + "");
       this.getHero1HP().setText(one.getHp() + "");
       this.getHero1Def().setText(one.getArmor().getDef() + "");
       this.getHero1Dmg().setText(one.getStr() + one.getWeapon().getDmg() + "");
        
       this.getHero2Agl().setText(two.getAgl() + "");
       this.getHero2Str().setText(two.getStr() + "");
       this.getHero2HP().setText(two.getHp() + "");
       this.getHero2Def().setText(two.getArmor().getDef() + "");
       this.getHero2Dmg().setText(two.getStr() + two.getWeapon().getDmg() + ""); 
       
       //Оружие и броня
       this.getHero1Weapon().setText(one.getWeapon().toString());
       this.getHero1Armor().setText(one.getArmor().toString());
       
       this.getHero2Weapon().setText(two.getWeapon().toString());
       this.getHero2Armor().setText(two.getArmor().toString());
       
       //Статистика попаданий
       this.hero1Hit.setText(one.getUnitStat().getHit() + "");
       this.hero1Miss.setText(one.getUnitStat().getMiss() + "");
       this.hero1HitPerc.setText(one.getUnitStat().getHitPerc());
       
       this.hero2Hit.setText(two.getUnitStat().getHit() + "");
       this.hero2Miss.setText(two.getUnitStat().getMiss() + "");
       this.hero2HitPerc.setText(two.getUnitStat().getHitPerc());
       
       
       
    }
    
    //BATTLE LOGIC
    //Битва с выводом победителей
    public AUnit fightWithLog(AUnit one, AUnit two){
    
    this.isBattle = true;    
  
    //Начало битвы вывод в фрейм    
    this.addBattleLog("******\nБитва между "+one.getName()+" и "+two.getName());
    this.addBattleLog(one.getAllStat());
    this.addBattleLog(two.getAllStat());
    this.addBattleLog("******\n");
    
    if (this.autoFight(one, two)){
        this.addBattleLog("*** Конец Боя ***\n Победитель "+one.getName());
        this.addBattleLog("\n*** Статистика Боя ***");
        this.addBattleLog(one.BattleFinalInfo());
        this.addBattleLog(two.BattleFinalInfo());
        return one;  
    }
    else{        
        this.addBattleLog("\n*** Конец Боя ***\n Победитель "+two.getName());
        this.addBattleLog("\n*** Статистика Боя ***");
        this.addBattleLog(one.BattleFinalInfo());
        this.addBattleLog(two.BattleFinalInfo());        
        return two;        
    }       
    }
    
    //Ручная возвращает победителя, если он есть в этом раунде  ****ГОВНОКОД****
    public AUnit nextRound(){
        
       this.isBattle = true;   //????
        
       if(one.getHp()>0 && two.getHp()>0){ 
            round(one,two);            
        }
       
       else {
           if(one.isAlive()) return one; //Если у первого есть хп - он победил
           else return two; //Иначе - второй
       }      
       
       //Говнокод
       return new SimpleMan();
   
    }
   
    //Перезапуск битвы
    public void restartBattle(AUnit one, AUnit two){
        
        //Настройка кнопок и текста
        this.battleStartSetup();
        
        //обеовить цвета
        this.resetColors();
        
        one.resetHealth();
        two.resetHealth();
        
        this.clearBattleLog();
        
        //очистить статистику
        this.one.getUnitStat().resetStats();
        this.two.getUnitStat().resetStats();
        
        this.turn = 1;
        
        this.setupHeroesOnFrame(one, two);
        
    }
    
    //Автоматическая битва Битва, победитель 1 - true, 2 - false
    public boolean autoFight(AUnit one, AUnit two){
 
        isBattle = true;
        
        while(one.getHp()>0 && two.getHp()>0){ 
            
            round(one,two);            
//            Thread.sleep(1500);
        }          
        
        //обнуляем ход
        turn = 1;        
        
        //Если у первого есть хп - он победил
        return one.isAlive();        
    }
    
    //Один ход битвы, несколько вызовов - несколько ходов
    void round(AUnit one, AUnit two){ 
        
        this.addBattleLog("*** "+ turn + " ход ***");
        this.addBattleLog(one.BattleInfo());
        this.addBattleLog(two.BattleInfo());
        
        //Сверяем инициативу для первого удара
        if(one.getInit()>two.getInit()){ 
            
            AttackAfterInit(one, two);               
        }        
        
        else if (two.getInit()>one.getInit()){
            
            AttackAfterInit(two, one);
        }
        
        else if (one.getInit()==two.getInit()){
            
            Random rnd = new Random();
            if(rnd.nextBoolean()) AttackAfterInit(one, two);
            else AttackAfterInit(two, one);            
        }
        
        //Увеличиваем ход, и добавляем пустую строку
        turn++;
        
        //Установка HP в фрейм!
        this.setupHeroesOnFrame(one, two);
        
       //Переход на след. строку
       this.addBattleLog("");
    }
    
    //Если урон есть - он отображается (Индикация урона)
    private void AttackLog(AUnit one, AUnit two){  
        
        //Сама атака и возвращение урона 
        Damage Dmg = one.Attack(two);
        
        //Если попал
        if(!Dmg.isMiss()){
            
            //Если критический
            if(Dmg.isCritical()){
                
                //Если есть оружие
                if(Dmg.getWeaponDmg() > 0) 
                   this.addBattleLog(one.getName()+" нанес "+Dmg.getAllDmg()+" урона критическим "
                            + "ударом используя "+one.getWeapon().getName()); 
                //Если нет оружия
                else
                    this.addBattleLog(one.getName()+" нанес "+Dmg.getAllDmg()+" урона критическим "
                            + "ударом");
            }    
            //Если не критический
            else{
                //Если есть оружие
                if(Dmg.getWeaponDmg() > 0)
                    this.addBattleLog(one.getName()+" нанес "+Dmg.getAllDmg()+" урона "
                            + "используя "+one.getWeapon().getName());
                //Если нет оружия
                else
                    this.addBattleLog(one.getName()+" нанес "+Dmg.getAllDmg()+" урона");                  
                }
        }
            
        //Если промахнулся
        else{
            this.addBattleLog(one.getName()+" промахнулся"); 
            
            //ПОДСВЕТКА УКЛОНЕНИЯ!!
            
        }
          
    }
    
    //Подсветка в интерфейсе
    public void resetColors(){
        this.hero1Panel.setBackground(new Color(240, 240, 250));
        this.hero2Panel.setBackground(new Color(240, 240, 250));
    }
    
    public void heroWin(AUnit unit){
        
        if(unit.isAttacking()) this.hero1Panel.setBackground(new Color(100, 200, 150));
        else this.hero2Panel.setBackground(new Color(100, 200, 150));
        
        //!!!!!!!!!!!!!!1 ОБЬЕДИНИТЬ IS BATTLE И СДЕЛАТЬ МЕТОД КОНЦА БИТВЫ
        this.isBattle = false;
        this.btnNextTurn.setEnabled(false);
        this.btnAutoFight.setEnabled(false);
        
        this.labelTurn.setText("Битва окончена");
        
    }
   
    //Порядок атак, после сверения инициативы
    private void AttackAfterInit(AUnit one, AUnit two){ 
        
        //1 потом 2
            AttackLog(one, two);
            
            //Если второй после удара жив, то он атакует в ответ
            if(two.isAlive()){
            
                //Атакует второй
                AttackLog(two, one);
                
                if(!one.isAlive()) {
                    this.addBattleLog(one.getName()+" умер");
                    //Подсветка победителя
                    this.heroWin(two);
                } 
            }
            
            else {
                this.addBattleLog(two.getName()+" умер");
                //Подсветка победителя
                this.heroWin(one);
            }
    }  
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBox;
    private javax.swing.JTextArea battleLogTextArea;
    private javax.swing.JButton btnAutoFight;
    private javax.swing.JButton btnChangeWeapon;
    private javax.swing.JButton btnNextTurn;
    private javax.swing.JButton btnRestartFight;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JTextField hero1Agl;
    private javax.swing.JTextField hero1Armor;
    private javax.swing.JLabel hero1ArmorImage;
    private javax.swing.JTextField hero1Def;
    private javax.swing.JTextField hero1Dmg;
    private javax.swing.JTextField hero1HP;
    private javax.swing.JLabel hero1Hit;
    private javax.swing.JLabel hero1HitPerc;
    private javax.swing.JLabel hero1Image;
    private javax.swing.JLabel hero1Miss;
    private javax.swing.JPanel hero1Panel;
    private javax.swing.JPanel hero1StatPanel;
    private javax.swing.JPanel hero1StatPanel1;
    private javax.swing.JTextField hero1Str;
    private javax.swing.JTextField hero1Weapon;
    private javax.swing.JLabel hero1WeaponImage;
    private javax.swing.JTextField hero1name;
    private javax.swing.JTextField hero2Agl;
    private javax.swing.JTextField hero2Armor;
    private javax.swing.JLabel hero2ArmorImage;
    private javax.swing.JTextField hero2Def;
    private javax.swing.JTextField hero2Dmg;
    private javax.swing.JTextField hero2HP;
    private javax.swing.JLabel hero2Hit;
    private javax.swing.JLabel hero2HitPerc;
    private javax.swing.JLabel hero2Image;
    private javax.swing.JLabel hero2Miss;
    private javax.swing.JPanel hero2Panel;
    private javax.swing.JTextField hero2Str;
    private javax.swing.JTextField hero2Weapon;
    private javax.swing.JLabel hero2WeaponImage;
    private javax.swing.JTextField hero2name;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel labelAttacking;
    private javax.swing.JLabel labelBattleBetween;
    private javax.swing.JLabel labelBattleBetween1;
    private javax.swing.JLabel labelBattleLog;
    private javax.swing.JLabel labelDefencing;
    private javax.swing.JLabel labelHero1Agl;
    private javax.swing.JLabel labelHero1Armor;
    private javax.swing.JLabel labelHero1Def;
    private javax.swing.JLabel labelHero1Dmg;
    private javax.swing.JLabel labelHero1HP;
    private javax.swing.JLabel labelHero1Hit;
    private javax.swing.JLabel labelHero1HitPerc;
    private javax.swing.JLabel labelHero1Miss;
    private javax.swing.JLabel labelHero1Name;
    private javax.swing.JLabel labelHero1Status;
    private javax.swing.JLabel labelHero1Str;
    private javax.swing.JLabel labelHero1Weapon;
    private javax.swing.JLabel labelHero2Agl;
    private javax.swing.JLabel labelHero2Armor;
    private javax.swing.JLabel labelHero2Def;
    private javax.swing.JLabel labelHero2Dmg;
    private javax.swing.JLabel labelHero2HP;
    private javax.swing.JLabel labelHero2Hit;
    private javax.swing.JLabel labelHero2HitPerc;
    private javax.swing.JLabel labelHero2Miss;
    private javax.swing.JLabel labelHero2Name;
    private javax.swing.JLabel labelHero2Status;
    private javax.swing.JLabel labelHero2Str;
    private javax.swing.JLabel labelHero2Weapon;
    private javax.swing.JLabel labelTurn;
    private javax.swing.JPanel logPanel;
    // End of variables declaration//GEN-END:variables
}
